#!/usr/bin/env python3
"""Lay the narration lines out on one clock and export it for the renderer, mixer and captions.

Writes:
  build/timeline.json   absolute times for scenes, lines, words and cues
  video/timeline.js     same data as `window.TIMELINE = ...` (so preview.html works from disk)
  out/<slug>.srt        captions
"""
import json
import os
import sys

sys.path.insert(0, os.path.dirname(__file__))
from common import BUILD, ROOT, load_narration, slug  # noqa: E402


def srt_time(t):
    ms = int(round(t * 1000))
    h, ms = divmod(ms, 3600_000)
    m, ms = divmod(ms, 60_000)
    s, ms = divmod(ms, 1000)
    return f"{h:02d}:{m:02d}:{s:02d},{ms:03d}"


def caption_chunks(words, max_chars=60):
    """Split a line into caption chunks, preferring sentence ends, then commas/colons, near the middle."""
    text = " ".join(w["w"] for w in words)
    if len(text) <= max_chars or len(words) < 4:
        return [words]
    best, best_score = None, None
    for k in range(2, len(words) - 1):
        left = len(" ".join(w["w"] for w in words[:k]))
        balance = abs(left - len(text) / 2) / len(text)
        end = words[k - 1]["w"]
        bonus = 0.5 if end.endswith((".", "?", "!")) else 0.3 if end.endswith((",", ":", ";")) else 0.0
        score = balance - bonus
        if best_score is None or score < best_score:
            best, best_score = k, score
    return caption_chunks(words[:best], max_chars) + caption_chunks(words[best:], max_chars)


def main():
    narr = load_narration()
    SLUG = slug(narr)
    vo = json.loads((BUILD / "vo.json").read_text())
    align = json.loads((BUILD / "alignment.json").read_text())
    durs = {(l["scene"], l["index"]): l for l in vo["lines"]}

    t = narr["leadIn"]
    scenes, lines, cues = [], [], {}
    for si, scene in enumerate(narr["scenes"]):
        first_start = t
        for i, line in enumerate(scene["lines"]):
            info = durs[(scene["id"], i)]
            a = align[f"{scene['id']}/{i}"]
            start, end = t, t + info["duration"]
            words = [{"w": w["w"], "start": round(start + w["start"], 3), "end": round(start + w["end"], 3)}
                     for w in a["words"]]
            for c, ct in a["cues"].items():
                cues[c if c not in cues else f"{scene['id']}.{c}"] = round(start + ct, 3)
                cues[f"{scene['id']}.{c}"] = round(start + ct, 3)
            lines.append({"scene": scene["id"], "index": i, "text": info["text"], "file": info["file"],
                          "start": round(start, 3), "end": round(end, 3), "words": words})
            last = i == len(scene["lines"]) - 1
            gap = line.get("pauseAfter", narr["sceneGap"] if last else narr["lineGap"])
            t = end + gap
        scenes.append({"id": scene["id"], "voStart": round(first_start, 3), "voEnd": round(lines[-1]["end"], 3)})

    # visual scene windows: each scene owns the time from just before its first line
    # until just before the next scene's first line
    lead = 0.45
    bounds = [{"id": "title", "start": 0.0}]
    for s in scenes:
        bounds.append({"id": s["id"], "start": round(max(0.0, s["voStart"] - lead), 3)})
    end_card_start = round(scenes[-1]["voEnd"] + 0.35, 3)
    bounds.append({"id": "end", "start": end_card_start})
    duration = round(end_card_start + narr["tail"], 3)
    for k, b in enumerate(bounds):
        b["end"] = bounds[k + 1]["start"] if k + 1 < len(bounds) else duration
        match = next((s for s in scenes if s["id"] == b["id"]), None)
        if match:
            b.update(voStart=match["voStart"], voEnd=match["voEnd"])

    timeline = {"title": narr["title"], "fps": narr["fps"], "duration": duration,
                "voice": {"provider": vo["provider"], **{k: v for k, v in vo["config"].items() if k != "style"}},
                "scenes": bounds, "lines": lines, "cues": cues}
    (BUILD / "timeline.json").write_text(json.dumps(timeline, indent=1, ensure_ascii=False))
    (ROOT / "video" / "timeline.js").write_text(
        "// generated by pipeline/timeline.py — do not edit\nwindow.TIMELINE = "
        + json.dumps(timeline, ensure_ascii=False) + ";\n")

    chunks = [c for line in lines for c in caption_chunks(line["words"])]
    srt = []
    for n, chunk in enumerate(chunks):
        start = chunk[0]["start"]
        end = chunk[-1]["end"] + 0.3
        if n + 1 < len(chunks):
            end = min(end, chunks[n + 1][0]["start"] - 0.02)
        srt.append(f"{n + 1}\n{srt_time(start)} --> {srt_time(end)}\n{' '.join(w['w'] for w in chunk)}\n")
    (ROOT / "out").mkdir(exist_ok=True)
    (ROOT / "out" / f"{SLUG}.srt").write_text("\n".join(srt))

    for b in bounds:
        print(f"  {b['id']:<11} {b['start']:6.2f} – {b['end']:6.2f}")
    print(f"duration {duration:.2f}s, {len(cues)} cues -> build/timeline.json, video/timeline.js, out/{SLUG}.srt")


if __name__ == "__main__":
    main()
